# Generated by Django 3.2 on 2021-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=50)),
                ('color', models.CharField(default='green', max_length=50)),
                ('school_image', models.ImageField(blank=True, null=True, upload_to='image/schools')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
