# Generated by Django 3.2 on 2021-05-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='color',
            field=models.CharField(default='#3d3f56', max_length=52),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/schools-logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default=2, max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=52, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/branches')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='schoolapp.school')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
