# Generated by Django 3.2.4 on 2021-07-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, default='image/branches/default_min.jpg', upload_to='images/branches'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='image/schools/default-min.jpg', upload_to='images/schools'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/schools-logo'),
        ),
    ]
