# Generated by Django 3.2.4 on 2021-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210705_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='yearly_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='yearly_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
