# Generated by Django 3.2.2 on 2021-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20210506_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='color',
            field=models.CharField(default='#3d3f56', max_length=52),
        ),
    ]
