# Generated by Django 3.2.4 on 2021-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20210723_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(db_index=True, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('school', 'name')},
        ),
    ]
