# Generated by Django 3.2.2 on 2021-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_branch_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default='image/schools/default.jpg', upload_to='image/schools'),
        ),
    ]
