# Generated by Django 3.2.2 on 2021-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='image/schools/default-min.jpg', upload_to='image/schools'),
        ),
    ]
