# Generated by Django 3.2.2 on 2021-05-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_alter_school_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='color',
            field=models.CharField(blank=True, default='#3d3f56', max_length=52),
        ),
    ]
