# Generated by Django 3.2.2 on 2021-05-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_alter_school_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, default='image/branches/default_min.jpg', null=True, upload_to='image/branches'),
        ),
    ]
