# Generated by Django 3.2.2 on 2021-05-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_alter_branch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, default='image/branches/default_min.jpg', upload_to='image/branches'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(null=True, upload_to='image/schools-logo'),
        ),
    ]
