# Generated by Django 3.2.2 on 2021-05-21 02:03

import core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20210521_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, default='image/branches/default_min.jpg', upload_to=core.functions.PathAndRename('image/branches')),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='image/schools/default-min.jpg', upload_to=core.functions.PathAndRename('image/schools')),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(null=True, upload_to=core.functions.PathAndRename('image/schools-logo')),
        ),
    ]
