# Generated by Django 3.2.2 on 2021-06-03 07:27

import core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_auto_20210521_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.functions.PathAndRename('image/schools-logo', 'logo')),
        ),
    ]
