# Generated by Django 3.2.4 on 2021-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_account',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
