# Generated by Django 3.2 on 2021-05-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='', upload_to='image')),
                ('address_city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_khoroo', models.CharField(blank=True, default='', max_length=255)),
                ('address_appartment', models.CharField(blank=True, default='', max_length=255)),
                ('dob', models.CharField(blank=True, default='', max_length=255)),
                ('register', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
