# Generated by Django 3.2 on 2021-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
