# Generated by Django 3.2.4 on 2021-07-19 10:24

import core.apps.authapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210705_0917'),
        ('authapp', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'This number is already registered!'}, max_length=20, validators=[core.apps.authapp.validators.validate_phone]),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('branch', 'phone')},
        ),
    ]
