# Generated by Django 3.2.4 on 2021-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210724_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email is already registered!'}, max_length=254, null=True, unique=True),
        ),
    ]
