# Generated by Django 3.2 on 2021-05-05 03:41

import core.apps.authapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'This number is already registered!'}, max_length=20, unique=True, validators=[core.apps.authapp.validators.validate_phone]),
        ),
    ]
