# Generated by Django 3.2 on 2021-05-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_customuser_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='group',
            new_name='groups',
        ),
    ]
