# Generated by Django 3.2 on 2021-05-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210506_0218'),
        ('authapp', '0011_auto_20210505_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school'),
        ),
    ]
