# Generated by Django 3.2 on 2021-05-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, default='jaja@jaja.com', error_messages={'unique': 'This email is already registered!'}, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
