# Generated by Django 3.2 on 2021-05-06 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schoolapp', '0003_auto_20210506_0218'),
        ('authapp', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schoolapp.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schoolapp.school'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
