# Generated by Django 3.2.2 on 2021-05-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20210510_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image/profiles/default.jpg', upload_to='image/profiles'),
        ),
    ]
