# Generated by Django 3.2.2 on 2021-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email is already registered!'}, max_length=254, null=True, unique=True),
        ),
    ]
