# Generated by Django 3.2.2 on 2021-05-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='dwqdwq', max_length=56),
            preserve_default=False,
        ),
    ]
