# Generated by Django 3.2.2 on 2021-05-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_alter_customuser_firstname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='seen_datasheet',
            field=models.IntegerField(blank=True, choices=[(1, 'Created from datasheet'), (2, 'Student and registered in datasheet'), (3, 'Created from student')], default=3),
        ),
    ]
