version: "3.7"

services:
    sms_server:
        env_file:
            - .env
        build:
            context: .
        command: gunicorn core.wsgi --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
    sms_client:
        build:
            context: ../sms-frontend
        volumes:
            - react_build:/app/build 
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - react_build:/var/www/react
        depends_on: 
            - sms_server
            - sms_client
volumes:
    react_build: