# Generated by Django 3.2.2 on 2021-05-13 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_alter_school_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('classapp', '0006_alter_calendar_unique_together'),
        ('datasheetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='schoolapp.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasheets', to='classapp.lesson'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_datasheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasheets', to='datasheetapp.status'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
