# Generated by Django 3.2.4 on 2021-06-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='register_type',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'In Person'), (3, 'Facebook'), (4, 'Instagram'), (5, 'Website')], default=0),
        ),
    ]
