# Generated by Django 3.2.4 on 2021-07-06 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210705_0917'),
        ('datasheetapp', '0002_status_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_statuses', to='schoolapp.branch'),
        ),
    ]
