# Generated by Django 3.2.2 on 2021-05-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_alter_school_image'),
        ('datasheetapp', '0002_auto_20210513_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_statuses', to='schoolapp.branch'),
            preserve_default=False,
        ),
    ]
