# Generated by Django 3.2.4 on 2021-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0003_alter_status_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=26),
        ),
    ]
