# Generated by Django 3.2.2 on 2021-05-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0004_auto_20210513_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='label',
            new_name='name',
        ),
    ]
