# Generated by Django 3.2.2 on 2021-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0005_rename_label_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='register_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Phone'), (2, 'In Person'), (3, 'Facebook'), (4, 'Instagram'), (5, 'Website')], null=True),
        ),
    ]
