# Generated by Django 3.2.2 on 2021-06-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0006_alter_datasheet_register_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
