# Generated by Django 3.2.2 on 2021-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheetapp', '0007_datasheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
