# Generated by Django 3.2.4 on 2021-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20210610_0456'),
        ('datasheetapp', '0008_alter_datasheet_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('branch', 'name')},
        ),
    ]
