# Generated by Django 3.2 on 2021-05-10 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('classapp', '0006_alter_calendar_unique_together'),
        ('utilityapp', '0002_auto_20210510_0905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('_class', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classapp.class')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='utilityapp.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paid', models.FloatField()),
                ('is_debit', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('paytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='utilityapp.paymentmethod')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='studentapp.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
