# Generated by Django 3.2 on 2021-05-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paytype',
            new_name='pay_type',
        ),
    ]
