# Generated by Django 3.2 on 2021-05-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20210506_1100'),
        ('studentapp', '0002_rename_paytype_payment_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=56, unique=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schoolapp.branch')),
            ],
        ),
    ]
