# Generated by Django 3.2 on 2021-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discounts',
            field=models.ManyToManyField(to='studentapp.Discount'),
        ),
    ]
