# Generated by Django 3.2 on 2021-05-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0002_auto_20210510_0905'),
        ('studentapp', '0004_student_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_payed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='utilityapp.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='studentapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='studentapp.Discount'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
