# Generated by Django 3.2 on 2021-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_auto_20210511_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='payment_payed',
            new_name='paid',
        ),
    ]
