# Generated by Django 3.2 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_rename_payment_payed_student_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid',
        ),
        migrations.AddField(
            model_name='discount',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='limited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
    ]
