# Generated by Django 3.2 on 2021-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_auto_20210511_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
