# Generated by Django 3.2 on 2021-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_alter_student_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
