# Generated by Django 3.2.2 on 2021-05-12 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('classapp', '0006_alter_calendar_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentapp', '0009_auto_20210511_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='limit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', '_class')},
        ),
    ]
