# Generated by Django 3.2.2 on 2021-05-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0002_auto_20210510_0905'),
        ('studentapp', '0011_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='utilityapp.paymentmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='studentapp.student'),
            preserve_default=False,
        ),
    ]
