# Generated by Django 3.2.2 on 2021-06-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0009_alter_exam_options'),
        ('studentapp', '0014_auto_20210521_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='classapp.calendar'),
            preserve_default=False,
        ),
    ]
