# Generated by Django 3.2.4 on 2021-07-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
