# Generated by Django 3.2 on 2021-05-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_auto_20210506_1100'),
        ('utilityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='schoolapp.branch'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='schoolapp.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
