# Generated by Django 3.2.4 on 2021-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20210610_0456'),
        ('utilityapp', '0002_auto_20210510_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('branch', 'name')},
        ),
    ]
