# Generated by Django 3.2.4 on 2021-07-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210705_0917'),
        ('utilityapp', '0002_auto_20210706_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='schoolapp.branch'),
        ),
        migrations.AlterField(
            model_name='status',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='schoolapp.branch'),
        ),
    ]
