# Generated by Django 3.2.4 on 2021-06-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20210610_0456'),
        ('utilityapp', '0003_auto_20210611_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('branch', 'name')},
        ),
    ]
