# Generated by Django 3.2.4 on 2021-07-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0004_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-default', '-id']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-default', '-id']},
        ),
    ]
