# Generated by Django 3.2.4 on 2021-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0004_alter_paymentmethod_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id']},
        ),
    ]
