# Generated by Django 3.2 on 2021-05-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolapp', '0004_auto_20210506_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Name is already registered!'}, max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schoolapp.branch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'Name is already regeistered!'}, max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.PositiveIntegerField(default=0, null=True)),
                ('is_online_pay', models.BooleanField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(default='#3d3f56', max_length=50)),
                ('sort', models.PositiveIntegerField(blank=True, null=True)),
                ('exam', models.PositiveIntegerField(default=0, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schoolapp.branch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
