# Generated by Django 3.2.4 on 2021-07-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_auto_20210705_0917'),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('branch', 'name')},
        ),
    ]
