# Generated by Django 3.2.4 on 2021-08-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='curriculum')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='schoolapp.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='curriculums',
            field=models.ManyToManyField(blank=True, to='classapp.Curriculum'),
        ),
    ]
