# Generated by Django 3.2.4 on 2021-08-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
        ('classapp', '0002_auto_20210803_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='schoolapp.school'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('school', 'name')},
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='branch',
        ),
    ]
