# Generated by Django 3.2.4 on 2021-07-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
    ]
