# Generated by Django 3.2 on 2021-05-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_calendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('_class', 'day', 'start_time')},
        ),
    ]
