# Generated by Django 3.2.4 on 2021-07-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
