# Generated by Django 3.2 on 2021-05-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_alter_calendar_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='room',
        ),
        migrations.AddField(
            model_name='calendar',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar', to='classapp.room'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='_class',
            field=models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='classapp.class'),
        ),
    ]
