# Generated by Django 3.2.6 on 2021-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_auto_20210806_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='file',
            field=models.FileField(upload_to='curriculums'),
        ),
    ]
