# Generated by Django 3.2.6 on 2021-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_alter_curriculum_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='file',
            field=models.FileField(upload_to='curriculum'),
        ),
    ]
