# Generated by Django 3.2.2 on 2021-05-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_alter_calendar_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('total_mark', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('_class', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classapp.class')),
            ],
        ),
    ]
