# Generated by Django 3.2.2 on 2021-06-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_school_logo'),
        ('classapp', '0007_exam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('branch', 'name')},
        ),
    ]
