# Generated by Django 3.2.4 on 2021-06-14 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classapp', '0009_alter_exam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='classapp.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='authapp.customuser'),
            preserve_default=False,
        ),
    ]
