# Generated by Django 3.2.4 on 2021-06-24 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0010_auto_20210614_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 3, 21, 4, 285781, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('room', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day',
        ),
    ]
