# Generated by Django 3.2.4 on 2021-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0011_auto_20210624_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
